name: CLICK-LOG-SERVER CI, DOCKER BUILD

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  # test
jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install 

      - name: Run tests
        env:
          NODE_ENV: test
          CLICK_DATABASE_URL: ${{ secrets.CLICK_DATABASE_URL }}
          CPM_DATABASE_URL: ${{ secrets.CPM_DATABASE_URL }}
        run: pnpm test:e2e
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kaburi/click-log-server:latest, kaburi/click-log-server:${{ github.run_number }}         
